root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"


[build]
# Instead of building for debug with Delve
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen=:2345 --api-version=2 ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules"]
delay = 1000
stop_on_error = true
log = "air.log"
send_interrupt = true
kill_delay = "2s"

[log]
main_only = false
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
